### ISSUE TITLE
Rework README to focus on first time users

### ISSUE THREAD

**Issue by donovanmuller** [AbsaOSS/k8gb#101]
Given someone that is looking for a cloud native, Kubernetes native GSLB solution and who finds this project. The `README` should concisely and simply answer the following questions:

* What problem does it solve? 
* How does it solve the problem? (Briefly, simply and with links to detailed docs)
* How do I run it locally to see how it works (Quick start)
* If I wanted to contribute, what should I know and how could I setup my local development environment (see #100)

The goal of the `README` should leave no doubt as to what this project does, how it does it and an easy, quick way to try it out.

**Comment by donovanmuller** [comment]
Some guides on good structure's for a `README`:

* https://github.com/matiassingers/awesome-readme
* https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
* https://github.com/othneildrew/Best-README-Template

**Comment by ytsarev** [comment]
@donovanmuller do you think current state of readme is good enough? since creation of this ticket it was amended with multiple stuff like local deployment and step-by-step deployment howto

**Comment by donovanmuller** [comment]
Yeah, looks fine for now. 👍
