### ISSUE TITLE
Makefile refactoring

### ISSUE THREAD

**Issue by kuritka** [AbsaOSS/k8gb#109]
Makefile targets are dependent on `full.sh` and environment variables declared at the same file.
 
- refactor Makefile to `GNU call Functions`  to get rid of dependencies on `full.sh`. 
- refactor all places where `full.sh` is used (i.e. terratest build pipe)

**Comment by kuritka** [comment]
Hi @ytsarev, if you have time, please look on the report below. If there is something which obviously shouldn't be in Makefile (obsolete, we don't use it,...), let me know.  

 - **bold** - moved to new Makefile and accessible `make <target>`
 - ~crossed out~ - functioality is moved to new Makefile but not accessible via targets
 - normal text - ready to move to new makefile, I'm trying to keep it as much lightweight as possible 

# old

 - all
 - bundle
 - bundle-build
 - **clean-test-apps**
 - controller-gen
 - ~create-k8gb-ns~
 - ~create-test-ns~
 - debug-local
 - debug-test-etcd
 - **demo-failover**
 - **demo-roundrobin**
 - deploy
 - ~deploy-first-k8gb~
 - **deploy-full-local-setup**
 - ~deploy-gslb-cr~
 - ~deploy-gslb-operator~
 - **deploy-gslb-operator-14**
 - deploy-local-cluster
 - ~deploy-local-ingress~
 - ~deploy-second-k8gb~
 - ~deploy-test-apps~
 - ~deploy-two-local-clusters~
 - **destroy-full-local-setup**
 - destroy-local-cluster
 - ~destroy-two-local-clusters~
 - **dns-smoke-test**
 - **dns-tools**
 - docker-build
 - docker-push
 - docker-test-build-push
 - fmt
 - generate
 - infoblox-secret
 - **init-failover**
 - **init-round-robin**
 - install
 - kustomize
 - **lint**
 - manager
 - manifests
 - **reset (NEW)**
 - run
 - **start-test-app**
 - **stop-test-app**
 - **terratest**
 - test
 - **test-failover**
 - **test-round-robin**
 - uninstall
 - ~use-first-context~
 - ~use-second-context~
 - **version**
 - vet
 - ~wait-for-gslb-ready~
 - ~wait-for-nginx-ingress-ready~


# new

 - clean-test-apps
 - demo-failover
 - demo-roundrobin
 - deploy-full-local-setup
 - destroy-full-local-setup
 - deploy-gslb-operator-14
 - dns-smoke-test
 - dns-tools
 - init-failover
 - init-round-robin
 - lint
 - **list (NEW)**
 - **reset (NEW)**
 - start-test-app
 - stop-test-app
 - terratest
 - test-failover
 - test-round-robin
 - version

**Comment by ytsarev** [comment]
looks like a great reduction of exposed make targets 👍 Looks like `test-*` targets can be removed as we have `demo-*` ones with similar functionality
