### ISSUE TITLE
Document metrics exposure via Prometheus Operator

### ISSUE THREAD

**Issue by somaritane** [AbsaOSS/k8gb#119]
Spin off from #47 
OhMyGLB supports integration with Prometheus Operator thanks to Operator SDK native support.
However, actual procedure of Prometheus Operator setup for proper scraping is not clear, so it makes sense to reflect it in OhMyGLB documentation.

**Comment by ytsarev** [comment]
@somaritane Just to clarify - there are no proper upstream Prometheus Operator docs for it ?

**Comment by somaritane** [comment]
> @somaritane Just to clarify - there are no proper upstream Prometheus Operator docs for it ?
There are. 
However there are several sources of information for those trying to install Prometheus Operator and setup metrics scraping for OhMyGLB there: 
https://github.com/coreos/prometheus-operator#prometheus-operator-vs-kube-prometheus-vs-community-helm-chart
and some installation options are not exactly obvious: https://github.com/helm/charts/issues/11310
So I think it makes sense to simplify user experience and provide clear setup instructions describing necessary setup options.

**Comment by ytsarev** [comment]
Issue is pretty much outdated, we might return to that during the work on observability Issues
