### ISSUE TITLE
Consider the switch from kind to k3d

### ISSUE THREAD

**Issue by ytsarev** [AbsaOSS/k8gb#141]
We already made some experiments with k3d which looked very good in terms of speed and performance, the only visible blocker was inability to have the test on the same network as in 
https://github.com/rancher/k3d/issues/111

Looks like the issue is solved in recent k3d version and we might give it another shot as we definitely want faster test cycle both locally and within ci/cd pipelines

**Comment by kuritka** [comment]
```
time k3d cluster create k3d-TEST

real    0m22.658s
user    0m2.139s
sys     0m1.791s
```

```
time kind create cluster --name=kind-TEST

real    0m35.984s
user    0m1.551s
sys     0m1.133s
```

**Comment by ytsarev** [comment]
Apparently it is not so critical deviation to worth a switch

**Comment by k0da** [comment]
@kuritka do you have node images cached? would be nice to see results if node image is not downloaded

**Comment by kuritka** [comment]
Thx for comments, maybe more relevant statistic:

![Screenshot 2020-11-24 at 16 59 27](https://user-images.githubusercontent.com/7195836/100118730-6b879b80-2e76-11eb-87c0-37445cf74857.png)

```
time kind create cluster --name=test-kind --config=deploy/kind/cluster.yaml
real    2m25.964s
user    0m4.373s
sys     0m3.168s
```

delete and run again
```
time kind create cluster --name=test-kind --config=deploy/kind/cluster.yaml
real    1m8.060s
user    0m4.774s
sys     0m3.098s
```

delete and run again
```
time kind create cluster --name=single-kind
real    0m23.073s
user    0m1.254s
sys     0m0.765s
```

>> prune all containers and images <<

```
time k3d cluster create multiserver --servers 3
real    1m25.317s
user    0m6.233s
sys     0m5.023s
```

```
time k3d cluster create multiserver --servers 3
real    0m43.637s
user    0m3.724s
sys     0m2.967s
```

delete and run singleserver !!!!!
```
time k3d cluster create single1
real    0m11.381s
user    0m1.136s
sys     0m0.907s
time k3d cluster create single2
real    0m11.381s
user    0m1.136s
sys     0m0.907s

```

**Comment by k0da** [comment]
I'd say k3d is twice faster, but since gitub action runner (public) contains kind already, result might be different

**Comment by somaritane** [comment]
Performance aside, I see that k3d is quite feature rich and configurable, and all this by command options, without complex config. You can easily expand existing cluster by adding nodes in runtime. Also with recent [v3.3.0 release](https://github.com/rancher/k3d/releases/tag/v3.3.0) they fixed regression with missing env vars support, so it has support for corporate proxies as well. I'd give it a try.

**Comment by k0da** [comment]
@somaritane I'm afraid to guess who made commits :)

**Comment by somaritane** [comment]
@k0da I wish it was me, but not this time :-D
