### ISSUE TITLE
Feature Request to Possibly Host more than one DNS Zones on K8gb

### ISSUE THREAD

**Issue by Zak-Anderson** [AbsaOSS/k8gb#151]
There is a possible issue that we need to have Separate DNS Zones for different Datacenters to cater for people who can only run Active Passive and then also hvae the GLB

Example is DC1-us.k8gb.gb and DC2-us.k8gb.gb then also DC.k8gb.gb

The request is to add support to host multiple DNS Zones in K8GB and not just one zone

**Comment by donovanmuller** [comment]
This is however not in the domain of GSLB anymore is it? 

`DC1-us.k8gb.gb` and `DC2-us.k8gb.gb` will in no way have any _global_ load balancing strategy applied to them as they are DC (Datacenter)/region specific.

IMHO this is not something k8gb should handle as this is not GSLB related, unless the scope of this project changes. DNS level "load balancing" is required for GSLB concerns but this feature seems to allow for a convenient way to configure DNS records for DC/region specific Ingress, with nothing to do with load balancing. I'm just concerned we are drifting away from the core responsibilities k8gb is meant to handle...

**Comment by ytsarev** [comment]
@donovanmuller Generally agree but I see it a little bit differently. 

k8gb 
1. create GSLB enabled dns record of e.g.  `DC.k8gb.gb`
2. It also creates `DC-us` and `DC-eu` following convention over configuration so the clusters/workloads behind  GSLB can be deterministically accessed directly bypassing LB strategy. Local DNS load-balancing is a nice side-effect of it.
3. No current Gslb spec modification required as again it will be convention only
4. This feature can be enabled/disabled in operator configuration

**Comment by donovanmuller** [comment]
I disagree with point 2 in principal:

> Local DNS load-balancing is a nice side-effect of it.

DNS is a poor local load balancer (TTL, no advanced strategies around least connection, etc.) and you can achieve the better results with other projects or configurations. If the main goal of point 2 is to make DNS automation easier, then that should be the responsibility of other projects/tools suited to that goal. 

> deterministically accessed directly bypassing LB strategy

This also implies that every Ingress resource could handle local load balancing independently, which is generally not the case. DNS would either point to a layer 4 load balancer (via a shared VIP potentially) in front of the ingress node IPs or the ingress nodes themselves but at an ingress _controller_ level, not at an individual Ingress resource level.

**Comment by ytsarev** [comment]
@donovanmuller / @Zak-Anderson any objections I close this one? Seems out of k8gb scope in the end

**Comment by donovanmuller** [comment]
@ytsarev happy to close from my side. I agree it's beyond the scope of this project.

**Comment by ytsarev** [comment]
@Zak-Anderson feel free to reopen if needed

**Comment by Zak-Anderson** [comment]
Happy to close
