### ISSUE TITLE
Support for NS1 Managed DNS

### ISSUE THREAD

**Issue by somaritane** [AbsaOSS/k8gb#202]
Consider adding Support for NS1 edgeDNS, as further step to promote k8gb in community.

- NS1 is supported provider by [external-dns](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/ns1.md), we should be able to utilize external-dns capabilities for zone delegation without the need for [direct API calls](https://ns1.com/api) 
- Split-brain control support is out of the scope until we have more consolidated approach on split-brain management.
- NS1 provider needs `NS1_APIKEY` token to wired to external-dns Deployment as environment variable.

**Comment by ytsarev** [comment]
Implemented by https://github.com/AbsaOSS/k8gb/pull/217
