### ISSUE TITLE
Replace k8gb.io/primarygeotag annotation with k8gb.io/primary-geotag

### ISSUE THREAD

**Issue by somaritane** [AbsaOSS/k8gb#210]
I know this is minor issue, and there are no strict conventions on [k8s annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/).
But `primary` and `geotag` in `k8gb.io/primarygeotag` are two separate words, so it's better to separate them with `dash` in order to make annotation more readable, avoid authoring errors, and also align with the style used by existing Ingress Controllers known to community (e.g. https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/, https://doc.traefik.io/traefik/v1.7/configuration/backends/kubernetes/#general-annotations): 
```diff
--- k8gb.io/primarygeotag
+++ k8gb.io/primary-geotag
```

**Comment by somaritane** [comment]
In order to maintain backwards compatibility with existing API, we can add `k8gb.io/primary-geotag` as alternative and deprecate `k8gb.io/primarygeotag` later.

**Comment by ytsarev** [comment]
No issues with the direct switch imho.
