### ISSUE TITLE
terratests - Possible race condition

### ISSUE THREAD

**Issue by kuritka** [AbsaOSS/k8gb#211]
The pictures below show the result of two consecutive test runs. Very often it happens that `TestK8gbIngressAnnotationFailover, TestK8gbIngressAnnotationRR` do not pass. Please investigate and fix the issue. Because the tests sometimes pass, and sometimes don't, I think the issue is race condition. I must add it that both kind and k3d errors occur.

![Screenshot 2020-12-03 at 09 19 51](https://user-images.githubusercontent.com/7195836/100982701-b4131900-3548-11eb-9497-6e64f21ba97e.png)

![Screenshot 2020-12-03 at 09 24 03](https://user-images.githubusercontent.com/7195836/100983204-4adfd580-3549-11eb-9143-96e0dbe203e5.png)

**Comment by ytsarev** [comment]
Do you have full error logs? It's hard to say from the screenshots but the failures seem to happen in different places
