### ISSUE TITLE
Move away from coreos etcd-operator

### ISSUE THREAD

**Issue by ytsarev** [AbsaOSS/k8gb#220]
We need to consider other etcd-operator options as current one is 

* Not maintained anymore, see readonly status at https://github.com/coreos/etcd-operator
* Doesn't fulfill its mission - two etcd processed were OOMkilled on the long-running cluster and operator failed to automatically recover the etcd quorum

So we can either find some another community one or write a new controller ourselves

**Comment by moshloop** [comment]
https://github.com/Quentin-M/etcd-cloud-operator seems to be a little more maintained

**Comment by k0da** [comment]
can be closed per https://github.com/AbsaOSS/k8gb/pull/292

**Comment by ytsarev** [comment]
I would say *should* be closed! Thanks a ton
