### ISSUE TITLE
Add Arm support

### ISSUE THREAD

**Issue by donovanmuller** [AbsaOSS/k8gb#243]
Binary and resource support for the Arm architecture would be be beneficial for use cases such as [EKS with Arm instances](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-eks-support-for-arm-based-instances-powered-by-aws-graviton-now-generally-available/)

**Comment by k0da** [comment]
https://github.com/AbsaOSS/k8gb/pull/326 brings CoreDNS support for aarch64

**Comment by k0da** [comment]
Just tested k8gb on EKS aarch64, it works great.
