### ISSUE TITLE
QUESTION? Upgrade to sigs.k8s.io/controller-runtime v0.8.1

### ISSUE THREAD

**Issue by kuritka** [AbsaOSS/k8gb#278]
Dependabot [wants update](https://github.com/AbsaOSS/k8gb/pull/277/commits/ac1bacb23e44357c12d802884bb99eddab811d9c) `sigs.k8s.io/controller-runtime` from `v0.6.4` to `v0.8.1`. 

Many [breaking changes](https://github.com/kubernetes-sigs/controller-runtime/releases) occurred between these versions, and it requires some refactor, see: [refactored branch](https://github.com/AbsaOSS/k8gb/compare/bump-controller-runtime)

I made all necessary refactoring and I had to upgrade to GO 1.15 which is required by `sigs.k8s.io/controller-runtime v0.8.1`.

on `v0.8.1` passed:
 - tests
 - terratest
 - local playground

[**BUT Operator SDK v1.3.0 defines controller-runtime v0.6.4**](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.3.0/#update-your-go-projects-controller-runtime-version-to-v064)

Should we stay with `v0.6.4`?

My proposal is to do following action:
 - stay with `v0.6.4`
 - ignore sigs.k8s.io/controller-runtime in dependabot 
 - upgrade to Go 1.15 (not necessary, but we should move forward here...)

**Comment by ytsarev** [comment]
I would vote to stay aligned with operator-sdk. We also can command dependabot to stick with minor 0.6 version for the time being
