### ISSUE TITLE
[helm chart] fsGroup not a valid securityContext field

### ISSUE THREAD

**Issue by raffaelespazzoli** [AbsaOSS/k8gb#293]
this seems to be an invalid field: https://github.com/AbsaOSS/k8gb/blob/7c9e66221b8c74997da1b8a10a9df553879a4d42/chart/k8gb/templates/external-dns/external-dns-ns1.yaml#L47

based on https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#securitycontext-v1-core

perhaps it should have been `runAsGroup`

Either way I'd recommend setting this at the pod level https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#podsecuritycontext-v1-core and making the values parametric as for example OCP is very specific about these kinds of things.

**Comment by ytsarev** [comment]
`fsGroup` was valid until the recent PSP deprecation, e.g. see https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#securitycontext-v1-core - it's there

IIRC it is just inherited from upstream external-dns tutorials and we probably don't really need it

@somaritane @kuritka @k0da  thoughts?
