### ISSUE TITLE
[Infoblox] Finalizer should not fail when provider can't communicate with underlying WAPI endpoint

### ISSUE THREAD

**Issue by somaritane** [AbsaOSS/k8gb#300]
User should be able to delete `gslb` object created in cluster, even if underlying EdgeDNS provider is not able to properly communicate to its respective API.
Currently, when Infoblox provider is not able to properly communicate with WAPI by various reasons, finalizer always returns the error:
```
2021-02-12T21:04:55.257+0100	ERROR	controller_gslb	Can’t finalize GSLB (...)	{“error”: “invalid character ‘<’ looking for beginning of value”}
```
As result, `gslb` object deletion gets stuck and blocks user application upgrade or deletion on clusters.
The only workaround is to patch the impacted `gslb` objects and remove finalizers, which doesn't scale.

k8gb version: `v.0.7.4`

**Comment by kuritka** [comment]
would be tested against  persistent connection: `@infoblox-single-connection`, 

Finalizer doesn't create a new connection, instead of that it reuse existing connection.

**Comment by ytsarev** [comment]
Or maybe it should as we actually cleaning up things like zone delegation config on the edgeDNS provider side.

The cluster operator always has the option to remove the finalizer manually in case of emergency.

@somaritane we discussed the above in person. Can we close this issue?

**Comment by somaritane** [comment]
> @somaritane we discussed the above in person. Can we close this issue?

Yes, I agree with that. Inability for finalizer to complete indicates some issues on EdgeDNS provider side, which should be properly addressed.
Otherwise we risk to have discrepancies in `gslb` custom resource state, such as orphaned DNS records etc.
Happy to close this one.
