### ISSUE TITLE
Add support for `k8gb.io/dns-ttl-seconds` and `k8gb.io/splitbrain-threshold-seconds` strategy annotations

### ISSUE THREAD

**Issue by somaritane** [AbsaOSS/k8gb#316]
`dnsTtlSeconds` and `splitBrainThresholdSeconds` strategy spec fields shoud be wired to `gslb` custom resource,
when one is created out of Ingress object with respective annotations.

Following annotation names are suggested:
- `splitBrainThresholdSeconds`: `k8gb.io/splitbrain-threshold-seconds`
- `dnsTtlSeconds`: `k8gb.io/dns-ttl-seconds`

**Comment by ytsarev** [comment]
It smells like recreation of the whole spec on annotation level. I am not sure we have to go down this road

**Comment by somaritane** [comment]
What should be criteria to decide which spec option is supported by Ingress annotations, and which one is not?
I feel like at least strategy related options should be wired.
If we don't want to wire them - does it mean that we're not considering Ingress with annotation as full-fledged citizen of `k8gb` configuration along with `gslb` custom resource?

**Comment by ytsarev** [comment]
@somaritane the initial idea of annotation approach was to just bound existing Ingress with new Gslb resource, not full control over this resource.

**Comment by kuritka** [comment]
Hello, I understand initial approach, but when I imagine the customer's view, he will probably expect both approaches to be compatible.

**Comment by ytsarev** [comment]
no objections, but it's gonna be fun when/if spec gets larger
