### ISSUE TITLE
Logger Enhancements

### ISSUE THREAD

**Issue by kuritka** [AbsaOSS/k8gb#331]
Because k8gb is constantly expanding, the requirements for monitoring the application are also increasing.
I'd like to mention a few of them:

 - DBG: There is no need to log everything all the time. Some messages only interests us when we debug the system or check its behavior. Cleaning log from too detailed information makes monitoring easier. On the other hand, when debugging system we need as detailed info as possible. I'd like to introduce boolean environment variable called `LOG_DEBUGGING`. When true, then prints `ERR + DBG + INFO + WRN`, otherwise `ERR + INFO + WRN`. 

- PROD / NONPROD : would be nice to distinguish between PROD and NONPROD systems. It could be Date format (for prod we want to show DateTime but only Time for nonprod). It could be format of message (plain print for NONPROD, json for PROD). Should distinguish by environment variable. For now bool variable `LOG_JSON`

- ERRORS handling: instead of printing entire stack trace including GO libraries, we should trace only stack related to k8gb

- please add your requirements for logging if any ?

To fulfill this purpose, I chose [zerolog](https://github.com/rs/zerolog) who has everything I mentioned earlier. In addition it has very high performance:

Library | Time | Bytes Allocated | Objects Allocated
-- | -- | -- | --
zerolog | 767 ns/op | 552 B/op | 6 allocs/op
⚡ zap | 848 ns/op | 704 B/op | 2 allocs/op
⚡ zap (sugared) | 1363 ns/op | 1610 B/op | 20 allocs/op
go-kit | 3614 ns/op | 2895 B/op | 66 allocs/op
lion | 5392 ns/op | 5807 B/op | 63 allocs/op
logrus | 5661 ns/op | 6092 B/op | 78 allocs/op
apex/log | 15332 ns/op | 3832 B/op | 65 allocs/op
log15 | 20657 ns/op | 5632 B/op | 93 allocs/op

Log a static string, without any context or printf-style templating:
Library | Time | Bytes Allocated | Objects Allocated
-- | -- | -- | --
zerolog | 50 ns/op | 0 B/op | 0 allocs/op
⚡ zap | 236 ns/op | 0 B/op | 0 allocs/op
standard library | 453 ns/op | 80 B/op | 2 allocs/op
⚡ zap (sugared) | 337 ns/op | 80 B/op | 2 allocs/op
go-kit | 508 ns/op | 656 B/op | 13 allocs/op
lion | 771 ns/op | 1224 B/op | 10 allocs/op
logrus | 1244 ns/op | 1505 B/op | 27 allocs/op
apex/log | 2751 ns/op | 584 B/op | 11 allocs/op
log15 | 5181 ns/op | 1592 B/op | 26 allocs/op

**Comment by kuritka** [comment]
@ytsarev @somaritane @k0da 
I was investigating potential outputs:

But first, shortly, how zerolog works: 
It always keeps a record in the internal structure, which is marshalled to JSON. I can format JSON fields (i.e. `level` =>`l`, `caller` => `c` etc...  ). Time is not formatted, instead timestamp integer is used (depending on settings i can choose between timestamp in seconds, timestamp in ms, timestamp in microseconds). JSON works well for non-human processing.
If I don't want JSON, I can implement custom formatter and print messages in more human readable form. i.e. I can format datetimes, fields, enable colors, enable links to source. 

I was thinking about three scenarios, how to print output:

In case we enable JSON and keep default info mode
![Screenshot 2021-03-03 at 13 04 53](https://user-images.githubusercontent.com/7195836/109803203-0daae280-7c21-11eb-9970-6db033c41faa.png)

In nonrod, no colors, datetime, link to origin
![Screenshot 2021-03-03 at 13 05 23](https://user-images.githubusercontent.com/7195836/109803256-1ef3ef00-7c21-11eb-9149-d3388a4612db.png)


Something is broken, and we want to debug. We don't care about dates but need more detailed information. JSON is disabled,  loglevel is trace or debug:
![Screenshot 2021-03-03 at 13 18 29](https://user-images.githubusercontent.com/7195836/109804795-f2d96d80-7c22-11eb-9f73-c36cbab76fda.png)

**Comment by somaritane** [comment]
> In nonrod, no colors, datetime, link to origin
@kuritka, by nonprod, do you mean local execution?

**Comment by kuritka** [comment]
Good question, can be used in general for default mode [JSON=FALSE, LOGGER_LEVEL != Debug or trace]. So for example `k8gb-test-nonprod-270`, locally as well. But we can do any combination we decide, it's just an example to discuss.

-  `LOGGER_JSON_MODE=true, LOGGER_LEVEL=Debug` print debug messages in json (not very usefull)
-  `LOGGER_JSON_MODE=true, LOGGER_LEVEL= Info` we can set for PORD
-  `LOGGER_JSON_MODE=false, LOGGER_LEVEL= Info` ideally for long running test environment, default
-  `LOGGER_JSON_MODE=false, LOGGER_LEVEL= Debug` we struggle with an error, trying to find an issue
- ...

Basically, I can extract everything including datetime formats etc.. but I wouldn't like to see complicated logger configuration. I rather extract one or two variables and smart logger will set based on input combination.
i.e. `LOGGER_JSON_MODE=true, LOGGER_LEVEL= debug` will print colored outputs with debug information

In order to that I was also thinking to remove LOGGER_JSON_MODE and come with LOGGER_OUTPUT_FORMAT having {JSON, CONSOLE_MONO, CONSOLE_COLORED}. Which provides us more options to do:
 - `LOGGER_OUTPUT_FORMAT=JSON, LOGGER_LEVEL= Debug` 
 - `LOGGER_OUTPUT_FORMAT=CONSOLE_MONO, LOGGER_LEVEL= Debug,` 
 - `LOGGER_OUTPUT_FORMAT=CONSOLE_MONO, LOGGER_LEVEL= info,` 
 - ...

**Comment by kuritka** [comment]
Good question, can be used in general [JSON=FALSE, LOGGER_LEVEL != Debug or trace]. So for example `270`, locally as well. But we can do any combination we decide, it's just an example to discuss.

-  `LOGGER_JSON_MODE=true, LOGGER_LEVEL=Debug` print debug messages in json (need to find use case for that)
-  `LOGGER_JSON_MODE=true, LOGGER_LEVEL= Info` we can set for PORD
-  `LOGGER_JSON_MODE=false, LOGGER_LEVEL= Info` ideally for long running test environment, default
-  `LOGGER_JSON_MODE=false, LOGGER_LEVEL= Debug` we struggle with an error, trying to find an issue
- ...

Basically, I can extract everything including datetime formats etc.. but I wouldn't like to see complicated logger configuration. I rather extract one or two variables and smart logger will set itself based on input combination.
i.e. `LOGGER_JSON_MODE=true, LOGGER_LEVEL= debug` will print colored outputs with debug information

In order to that I was also thinking to remove LOGGER_JSON_MODE and come with LOGGER_OUTPUT_FORMAT having {JSON, CONSOLE_MONO, CONSOLE_COLORED}. Which provides us more options to do:
 - `LOGGER_OUTPUT_FORMAT=JSON, LOGGER_LEVEL= Debug` 
 - `LOGGER_OUTPUT_FORMAT=CONSOLE_MONO, LOGGER_LEVEL= Debug,` 
 - `LOGGER_OUTPUT_FORMAT=CONSOLE_MONO, LOGGER_LEVEL= info,` 
 - ...

**Comment by somaritane** [comment]
@kuritka, few comments, questions below from me:

> In order to that I was also thinking to remove LOGGER_JSON_MODE and come with LOGGER_OUTPUT_FORMAT having {JSON, CONSOLE_MONO, CONSOLE_COLORED}. Which provides us more options to do

I support this, the simpler - the better.
User should be given power to chose a format depending on own conditions and environment.

I think however, that `json` should be used as default format, in this case we focus from beginning on real cluster scenarios, allowing  OOTB integration with logging solutions, like ELK, EFK etc.
Settings like `CONSOLE_MONO`, `CONSOLE_COLORED` are good for contributor's environment, and it's always possible to set them using envvar or in makefile.

On `CONSOLE_MONO`, `CONSOLE_COLOURED`: I find this naming somewhat misleading, as in case of `json` we still output to stdout and stderr. We should not mix the format with sink being used for logging (stdout, file, s3, etc).
So I'd suggest using values like `json`, `simple`.

As for color, I think instead of making it separate format, it makes sense to respect [NO_COLOR](https://no-color.org/) environment variable, and detect it by particular formatted if needed, we already use this approach in Makefile.

**Comment by somaritane** [comment]
@kuritka, another question I have on `package:source_line` (`main.go:103`) data in produced logs: is this something that is automatically provided by zerolog for every log.Info in the package, or do we need to instrument every package with logger specific settings in order to achieve that? 

> ![Screenshot 2021-03-03 at 13 05 23](https://user-images.githubusercontent.com/7195836/109803256-1ef3ef00-7c21-11eb-9149-d3388a4612db.png)

**Comment by kuritka** [comment]
Hi @somaritane , in order to `source-file:source_line`. Yes, I can configure whether it generates information. See example below:

With caller enabled:
![Screenshot 2021-03-05 at 09 46 45](https://user-images.githubusercontent.com/7195836/110090534-b418f400-7d97-11eb-8c69-7ba6ac2a3267.png)

With caller disabled:
![Screenshot 2021-03-05 at 09 49 33](https://user-images.githubusercontent.com/7195836/110090879-17a32180-7d98-11eb-82be-9f53aef07462.png)

JSON caller
![Screenshot 2021-03-05 at 09 50 13](https://user-images.githubusercontent.com/7195836/110090960-31446900-7d98-11eb-9b79-6746965ec23f.png)

JSON caller disabled
![Screenshot 2021-03-05 at 09 50 45](https://user-images.githubusercontent.com/7195836/110091017-43260c00-7d98-11eb-83d4-1a34e500b424.png)


Regarding env_vars inputs: 
yes, I can change to three input environment variables: reading level, no_color flag and whether output is json or simple.

**Comment by kuritka** [comment]
@somaritane, I just made some investigations,  besides ^^^  `source-file:source_line` symbols, is rather about compilation:

see my demo:
 `go install` with 40MB output;  path is absolute to build origin here. If you run on local system, it's clickable.
![Screenshot 2021-03-05 at 10 41 43](https://user-images.githubusercontent.com/7195836/110097485-61dbd100-7d9f-11eb-8072-56995ce7497e.png)

 `go install -ldflags '-s -w'` with 33.942MB; the path is absolute to build origin here. If you run on local system, it's clickable.
![Screenshot 2021-03-05 at 10 41 43](https://user-images.githubusercontent.com/7195836/110097485-61dbd100-7d9f-11eb-8072-56995ce7497e.png)

`go install -ldflags '-s -w' -trimpath` with 32.908MB
![Screenshot 2021-03-05 at 10 39 58](https://user-images.githubusercontent.com/7195836/110097297-250fda00-7d9f-11eb-9438-0642df6c4856.png)
