### ISSUE TITLE
Automate permutation testing

### ISSUE THREAD

**Issue by ytsarev** [AbsaOSS/k8gb#349]
To avoid regressions connected with the upgrade procedure we need to automatically test upgrade from current to future release before stabilizing the new version.

**Comment by ytsarev** [comment]
@kuritka @somaritane @k0da I guess we can close this one or do you envision more work in this area in foreseeable future?

**Comment by somaritane** [comment]
> @kuritka @somaritane @k0da I guess we can close this one or do you envision more work in this area in foreseeable future?

@ytsarev yep, I think we can close this one, the scope is pretty much fulfilled by #429 and #435. Just one thing, as I mentioned earlier, "Permutation" and "permutation testing" are quite a broad terms, let's rename the issue with "Automate upgrade testing" in order to avoid confusions.

**Comment by ytsarev** [comment]
@somaritane I was just trying to sound smart :D Closing this one
