### ISSUE TITLE
Issue when deleting ingress rule or annotations removal doesn't remove the gslb records

### ISSUE THREAD

**Issue by Zak-Anderson** [AbsaOSS/k8gb#361]
Hi Team

I have deployed the k8gb to a cluster with Kube 1.16.15

I have used the k8gb annotations for the ingress and deleted it

what I have found is that the gslb record does not get deleted but tries to get recreated although the ingress has been deleted.

is there a way by means of annotation removal or when ingress is deleted that the ingress >>>> gslb relationship works smoothly and seamlessly to delete the actual gslb record when the ingress is unannotated or deleted

I had to manually use

k delete gslb -n namespace namegslbingress

**Comment by ytsarev** [comment]
@kuritka it's not a bug. Annotations-based support was never meant to revert the initial ownership chain of Gslb -> automatically created Ingress under control. We created annotation-based propagation for the ease of adoption and integration with external tools to bootstrap Gslb CR.
We can definitely look into creation of the reverse ownership, but it's not something we didn't anticipate so re-labeling as enhancement.

**Comment by kuritka** [comment]
@ytsarev, thx for explaining 👍

**Comment by somaritane** [comment]
There's another scenario that gets impacted by current behavior: replacement of already created gslb custom resources to Ingresses with gslb annotations. 
In this case, user can't expect smooth automatic transition, as there's a need to manually intervene and delete all gslbs first.
And in case of self-healing GitOps deployments, this can get even more problematic.

**Comment by ytsarev** [comment]
We need to fix it soon then. Included in the current 0.8 milestone
