### ISSUE TITLE
Document internal components of k8gb

### ISSUE THREAD

**Issue by ytsarev** [AbsaOSS/k8gb#89]
We already have great design architecture docs in place, now we need to amend them with specific implementation details depicting open source components we are using to solve specific tasks, e.g.

* CoreDns to respond to DNS queries
* Dedicated ETCD to act as CoreDNS backend
* external DNS as a glue between DNSEndpoint CRDs and CoreDNS configuration
* Set of CRDs and k8s primitives that involved in k8gb operations 

Fancy diagrams are welcomed.

**Comment by donovanmuller** [comment]
Could I suggest we stick to using [Drawio](https://github.com/jgraph/drawio) as the design tool and committing the [source](https://github.com/AbsaOSS/ohmyglb/blob/master/docs/images/gslb-basic-multi-cluster.drawio) in addition to the exported image for consistency and maintainability.

**Comment by prachidamle** [comment]
@ytsarev I was looking at some docs related use of Infoblox by ohmyglb - what task does integration with Infoblox solve? Is there any existing doc I can check?

**Comment by ytsarev** [comment]
@prachidamle ohmyglb has concept of EdgeDNS zone and own DNS zone it is authoritative for
 See https://github.com/AbsaOSS/ohmyglb/blob/master/chart/ohmyglb/values.yaml#L11-L12

So in example above 
* EdgeDNS zone of `example.com` is controlled by Infoblox(or Route53 or any environment specific DNS solution in future)
* `cloud.example.com` is DNS Zone that is delegated to ohmyglb to serve DNS responses. So it will be capable to answer authoritatively to DNS queries like `app.cloud.example.com`

Automated ZoneDelegation configuration and associated split brain checks is exactly what Infoblox integrations solves, see  https://github.com/AbsaOSS/ohmyglb/pull/39 and https://github.com/AbsaOSS/ohmyglb/pull/44

Infoblox is currently only integrated EdgeDNS provider, we also plan Route53 and other cloud environments support ( https://github.com/AbsaOSS/ohmyglb/issues/53 ) 

We still need to cover EdgeDNS specifics properly in the docs, thanks a lot for your question.
