### ISSUE TITLE
Infoblox Zone Delegation not created under correct Auth Zone

### ISSUE THREAD

**Issue by Zak-Anderson** [AbsaOSS/k8gb#99]
What we have seen in Infoblox that we have a zone ohmyglb.test.good.org

if we have a delegated zone mynewglb "mynewglb.ohmyglb.test.good.org" that gets created with the Solution see that it creates duplicate zones 

pne in the parent zone inside "test.good.org" as a full record inside the test.good.org as mynewglb.ohmyglb inside test.good.org and not below the ohmyglb.test.goo.org as new delegated Zone.

**Comment by ytsarev** [comment]
@Zak-Anderson is it still valid/worth investigating?

**Comment by Zak-Anderson** [comment]
Hi

We have discussed this and looked at how it works and look as expected

**Comment by ytsarev** [comment]
Thanks, closing
